apiVersion: v1
kind: Service
metadata:
  name: service-backend
  labels:
    app: deployment-backend
spec:
  selector:
    app: deployment-backend
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  type: ClusterIP
