apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    app: deployment-frontend
spec:
  selector:
    app: deployment-frontend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: NodePort
