name: main

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  docker_username: gibbus2
  docker_password: ${{ secrets.GITHUB_TOKEN }}  
jobs:
  call-build:
    uses: ./.github/workflows/build.yaml

  call-docker-build-push:
    permissions:
        packages: write
    uses: ./.github/workflows/docker-build-push.yaml
    
  call-test:
    uses: ./.github/workflows/test.yaml

  call-deploy:
    needs: [call-docker-build-push]
    uses: ./.github/workflows/deploy.yml
    
